### ISSUE TITLE
Doesn't seem to work with Guile 3.0

### ISSUE THREAD

**Issue by emacsomancer** [alezost/guix.el#37] opened 2020-01-25 01:56 UTC
I end up with a lot of errors of the form:

```
;;; WARNING: loading compiled file /home/slade/.config/guix/current/lib/guile/3.0/site-ccache/guix/ui.go failed:
;;; In procedure load-thunk-from-memory: incompatible bytecode kind
```

**Comment by alezost** [comment] 2020-01-28 18:19
I guess this incompatibility happens because the latest Guix is compiled with Guile3 and Emacs-Guix you have installed in your profile is compiled with Guile2.  I think this can be fixed only on the Guix side: I mean, when the package definition of `emacs-guix` will be adjusted to use `guile-3.0` instead of `guile-2.2`.

**Comment by jellelicht** [comment] 2020-03-21 23:17
Emacs-Guix currently uses `@@`, so AFAIK won't work with `guile-3.0`.

**Comment by alezost** [comment] 2020-03-29 16:29
> Emacs-Guix currently uses `@@`, so AFAIK won't work with `guile-3.0`.

Do you mean Guile 3.0 does not support `@@`?  Then it is a big issue as Emacs-Guix uses multiple symbols that are not exported by Guix.

Here is a list of these symbols:

- `log-url` from `(guix scripts build)` module,
- `compressor-name`, `%compressors`, and `%formats` from `(guix scripts pack)` module,
- `search-path-environment-variables` from `(guix scripts package)` module,
- `operating-system-firmware` from `(gnu system)` module.

It would be good if Guix exported them, otherwise I would have to remove the according functionality from Emacs-Guix.

**Comment by Ambrevar** [comment] 2020-03-29 18:06
Maybe we should open a bug upstream for this! :)

**Comment by jellelicht** [comment] 2020-03-29 19:37
guix commit 65b510bbc4f2a9ce5bfe3355e6006e9d08f14532 seems to state:

    "Avoid @@, which doesn't work on Guile 3."

I am not sure if this is actually true for Guile 3, or just applies to
the way guix does things, but seeing as we depend on guix here, my guess
is that it is relevant either way :-)

**Comment by zimoun** [comment] 2020-05-29 09:21
@jellelicht The syntax `@@` is still used in Guix so I do not know if *"Avoid use of '@@'"* is specific to `clojure-utils` or not.

For example, `guix/scripts/{challenge,repl,publish}.scm` or `guix/store/database.scm` or etc..

@Ambrevar Is it a bug upstream? Why?

@alezost As discussed on [Gitlab Issue 20](https://gitlab.com/emacs-guix/emacs-guix/-/issues/20), the `REPL` does not start because of `%max-returned-list-size` on foreign distro and it fails to find the module `(gcrypt hash)`.  Now the `emacs-guix` package is compiled in Guix with Guile 3 and the dependencies seem right.  What could be wrong?

**Comment by Ambrevar** [comment] 2020-05-29 16:20
Not a bug, by "open a bug" I meant a report, in debbugs parlance.  I refered to the list of symbols mentioned by Alex.

**Comment by bon** [comment] 2020-06-13 08:55
Wait, isn't this exactly the kind of thing that guix is designed to cope with? Until such a time is `emacs-guix` is made to work with Guile 3, make a package definition of `emacs-guix` that works with Guile 2?

**Comment by alezost** [comment] 2021-01-01 16:03
I think it should work with Guile 3 properly now (after several recent commits).
If anyone still has some problems, please reopen this issue.

**Closed by alezost** 2021-01-01 16:03 UTC
